# Generated by Django 3.1.5 on 2021-07-22 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 7, 30, 13, 244038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 7, 30, 13, 244069, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
